title = "CloudyCluster"
baseURL = "https://inspiring-sinoussi-ea6b42.netlify.com/"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 2
    name = "Quickstart"
    url = "http://docs.cloudycluster.com/"
  [[menu.header]]
    weight = 3
    name = "Docs"
    url = "http://docs.cloudycluster.com/"
  [[menu.header]]
    weight = 4
    name = "Support"
    url = "/support"
  [[menu.header]]
    weight = 5
    name = "News"
    url = "/blog"
  [[menu.header]]
    weight = 6
    name = "Videos"
    url = "/video"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"
  home = "Home"
  twitterUserName = "themefisher"

  [params.slider]
    enable = true
    title = "Self Service Cloud HPC"
    subtitle = "COMPLETE WITH SCHEDULER, COMPUTE AND STORAGE BASED ON ORANGEFS, EFS AND S3.  CLOUDYCLUSTER COMES COMPLETE, READY TO COMPUTE WITH A WIDE VARIETY OF POPULAR OPEN HPC SOFTWARE"
    [[params.slider.btn]]
      name  = "Quickstart Guide" 
      url   = "http://docs.cloudycluster.com/"
    [[params.slider.btn]]
      name  = "Launce Cloudycluster" 
      url   = "https://aws.amazon.com/marketplace/pp/B01M71ZWE5?qid=1527735309119&sr=0-1&ref_=srh_res_product_title"

  [params.about]
    enable = true
    title = "CloudyCluster"
    btnText   = "Try Cloudycluster"
    btnURL    = "https://aws.amazon.com/marketplace/pp/B01M71ZWE5?qid=1527735309119&sr=0-1&ref_=srh_res_product_title"

    [[params.about.list]]
      listText  = "Begins with a Management Instance that is launched in your own AWS account."
    [[params.about.list]]
      listText  = "A simple but powerful Web-UI is then used to create a base HPC environment with Scheduler, Login instance and storage that you choose."
    [[params.about.list]]
      listText  = "After the HPC environment is created you can submit Torque(PBS) or Slurm jobs through CCQ, a meta-scheduler that is delivered with CloudyCluster."
    [[params.about.list]]
      listText  = "Once submitted, CCQ inspects the job and instantiates the instances dynamically and once ready releases the job to Torque(PBS) or Slurm to process the job."
    [[params.about.list]]
      listText  = "When all the jobs for that instance type are complete, CCQ tears down the instances before the billing cycle is complete, so you only pay for the runtime you need."

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title   = "A small title"
    content = "CloudyCluster is designed to look and feel similar to standard HPC environments, with login instances, scheduler, scratch storage and with the added capabilities of elastic compute instance creation. A group of researchers from Clemson University achieved a remarkable milestone while studying topic modeling, an important component of machine learning associated with natural language processing, breaking the record for creating the largest high-performance cluster by using more than 1,100,000 vCPUs on Amazon EC2 Spot Instances running in a single AWS region, accessed via CloudyCluster."
    image = "img/elastic_compute.png"

  [params.call]
    enable = true
    title = "CLOUDYCLUSTER MILLION+ CORE RUN ON AWS"
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."
    btnCaption   = "Try Cloudycluster"
    btnURL    = "https://aws.amazon.com/marketplace/pp/B01M71ZWE5?qid=1527735309119&sr=0-1&ref_=srh_res_product_title"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
